Update system_requirements.rst
NethServer/ns8-docs pull request #21
Opened 2023-07-05 14:45 UTC by DavidePrincipi

- Raise requirement to Debian 12
- Fix EL versions
- Remove arch (repeated above)

Refs https://github.com/NethServer/ns8-core/pull/415

Merge after it has been tagged and released!

2023-07-05 14:48 UTC, gsanchietti requested changes
Please leave fixed version for Rocky and Alma since those are not strictly rolling distros

2023-07-05 14:54 UTC, gsanchietti requested changes
Sorry, I didn't see that `>=` was gone.
Without it, we need to update this doc at least once a year

2023-07-05 14:58 UTC, gsanchietti commented
> Another reason for my previous change: remove both >= and the minor version! 😩

Original sentence `Rocky Linux <https://rockylinux.org/> >= 9.1` did not have this problem, you just added it :trollface:

2023-07-05 15:02 UTC, gsanchietti approved these changes

2023-07-06 12:10 UTC, stephdl approved these changes

2023-07-26 10:51 UTC, merged